package asm

import (
	"fmt"
	"io"
	"slices"

	"github.com/jenska/m68kasm/internal/asm/instructions"
)

type Program struct {
	Items         []any
	Labels        map[string]uint32
	DefinedLabels []DefinedLabel
	Origin        uint32
	SourceLines   []string
	Target        instructions.Target

	// Warnings collects non-fatal messages produced while assembling —
	// currently just checkEmulatedOn68060's "traps and is software-
	// emulated" notices, one per matching instruction, each already
	// prefixed with its source line. Populated by Assemble and its
	// variants; empty unless Target.CPU is CPU68060. Existing callers
	// that don't look at this field see no change in behavior.
	Warnings []string
}

// DefinedLabel captures a named label defined in source so that output formats
// can preserve stable label metadata without including parser-only symbols.
type DefinedLabel struct {
	Name    string
	Addr    uint32
	Line    int
	Section SectionKind
}

// ListingEntry captures the assembled bytes for a single source line so that a
// human-readable listing file can be generated.
type ListingEntry struct {
	Line  int
	PC    uint32
	Bytes []byte
}

// Assemble walks through the parsed program and encodes each instruction or data block.
// It resolves labels using the symbol table generated by the parser.
func Assemble(p *Program) ([]byte, error) {
	out, _, _, err := assemble(nil, nil, p, false)
	return out, err
}

// AssembleInto appends the assembled program bytes into dst and returns the resulting slice.
func AssembleInto(dst []byte, p *Program) ([]byte, error) {
	out, _, _, err := assemble(dst, nil, p, false)
	return out, err
}

// AssembleWithListing assembles the program and also returns a per-line listing
// describing the generated bytes at each program counter.
func AssembleWithListing(p *Program) ([]byte, []ListingEntry, error) {
	return AssembleWithListingInto(nil, p)
}

// AssembleWithListingInto appends the assembled program bytes into dst and
// returns both the resulting slice and listing metadata.
func AssembleWithListingInto(dst []byte, p *Program) ([]byte, []ListingEntry, error) {
	out, listing, _, err := assemble(dst, nil, p, true)
	return out, listing, err
}

// AssembleStream writes the assembled program bytes directly into w. The total
// number of bytes written is returned so that callers can pre-size buffers.
func AssembleStream(w io.Writer, p *Program) (int64, error) {
	_, _, written, err := assemble(nil, w, p, false)
	return written, err
}

// AssembleStreamWithListing writes the assembled program bytes directly into w
// while also returning a per-line listing of the emitted data.
func AssembleStreamWithListing(w io.Writer, p *Program) (int64, []ListingEntry, error) {
	out, listing, written, err := assemble(nil, w, p, true)
	_ = out
	return written, listing, err
}

func assemble(dst []byte, w io.Writer, p *Program, wantListing bool) ([]byte, []ListingEntry, int64, error) {
	out := dst
	if out == nil && w == nil {
		out = make([]byte, 0, 1024)
	}

	var listing []ListingEntry
	if wantListing {
		listing = make([]ListingEntry, 0, len(p.Items))
	}

	var written int64
	itemBuf := make([]byte, 0, 32)

	for _, it := range p.Items {
		var err error
		var warning string
		itemBuf, warning, err = assembleItem(itemBuf[:0], it, p.Labels, p.Target.CPU)
		if err != nil {
			return nil, nil, written, withSourceLines(err, p.SourceLines)
		}
		if warning != "" {
			if _, line, ok := itemLocation(it); ok {
				warning = fmt.Sprintf("line %d: %s", line, warning)
			}
			p.Warnings = append(p.Warnings, warning)
		}

		if w != nil {
			n, err := w.Write(itemBuf)
			if err != nil {
				return out, listing, written, err
			}
			written += int64(n)
		} else {
			out = append(out, itemBuf...)
		}

		if wantListing {
			pc, line, _ := itemLocation(it)
			entry := ListingEntry{PC: pc, Line: line}
			entry.Bytes = append(entry.Bytes, itemBuf...)
			listing = append(listing, entry)
		}
	}

	return out, listing, written, nil
}

func assembleItem(dst []byte, it any, labels map[string]uint32, cpu instructions.CPUKind) ([]byte, string, error) {
	switch x := it.(type) {
	case *Instr:
		ins := *x
		ins.Args = x.Args

		def := x.Def
		if def == nil {
			return nil, "", &Error{Line: x.Line, Col: x.Col, Err: fmt.Errorf("no definition for opcode")}
		}

		actualKinds := operandKinds(&ins.Args)
		form, err := selectForm(def, &ins, actualKinds)
		if err != nil {
			return nil, "", contextualizeAt(x.Line, x.Col, err)
		}
		if form.Validate != nil {
			if err := form.Validate(&ins.Args); err != nil {
				return nil, "", contextualizeAt(x.Line, x.Col, err)
			}
		}
		if !form.AllowFloatImm && argsHaveFloatImm(&ins.Args) {
			return nil, "", contextualizeAt(x.Line, x.Col, fmt.Errorf("floating-point immediate literal is not valid here"))
		}

		bytes, err := Encode(def, form, &ins, labels)
		if err != nil {
			return nil, "", contextualizeAt(x.Line, x.Col, err)
		}
		var warning string
		if cpu == instructions.CPU68060 {
			warning = checkEmulatedOn68060(def.Mnemonic, &ins.Args)
		}
		return append(dst, bytes...), warning, nil

	case *DataBytes:
		return append(dst, x.Bytes...), "", nil

	default:
		return nil, "", fmt.Errorf("unknown item type in program")
	}
}

// argsHaveFloatImm reports whether any operand carries a floating-point
// immediate literal (EAExpr.ImmIsFloat) — see FormDef.AllowFloatImm's
// own doc comment for why this centralized check exists.
func argsHaveFloatImm(a *instructions.Args) bool {
	return a.Src.ImmIsFloat || a.Dst.ImmIsFloat || a.Aux.ImmIsFloat || a.Aux2.ImmIsFloat
}

func selectForm(def *instructions.InstrDef, ins *Instr, actual []instructions.OperandKind) (*instructions.FormDef, error) {
	for i := range def.Forms {
		form := &def.Forms[i]
		if len(form.Sizes) > 0 {
			if !sizeAllowed(form.Sizes, ins.Args.Size) {
				continue
			}
		}
		// operKindsMatch already treats a zero-length expected list as
		// "match only a zero-length actual list" correctly on its own, so
		// this must not be skipped when form.OperKinds is empty: doing so
		// let a zero-operand form (e.g. TRAPcc's bare form) swallow a
		// same-size form that does take operands, silently discarding
		// them (see docs/design/cpu-family-support.md, milestone 5).
		if !operKindsMatch(form.OperKinds, actual) {
			continue
		}
		return form, nil
	}
	return nil, fmt.Errorf("no form matches operands/size for %s", def.Mnemonic)
}

// sizeAllowed reports whether sz is permitted by allowed. An empty allowed list
// means the form places no constraint on the size. Forms allow 1-3 sizes, so a
// linear scan is the right call here.
func sizeAllowed(allowed []instructions.Size, sz instructions.Size) bool {
	return len(allowed) == 0 || slices.Contains(allowed, sz)
}

func operandKinds(a *instructions.Args) []instructions.OperandKind {
	var kinds [5]instructions.OperandKind
	n := 0
	haveTarget := false
	if a.HasImmQuick {
		kinds[n] = instructions.OpkImmQuick
		n++
	} else if a.RegMaskSrc != 0 {
		kinds[n] = instructions.OpkRegList
		n++
	} else if a.FPRegMaskSrc != 0 {
		kinds[n] = instructions.OpkFPRegList
		n++
	} else if a.FPCtrlMaskSrc != 0 {
		kinds[n] = instructions.OpkFPCtrlRegList
		n++
	} else if a.Src.Kind != instructions.EAkNone {
		kinds[n] = operandKindFromEA(a.Src)
		n++
	} else if a.Target != "" || a.HasTargetAddr {
		kinds[n] = instructions.OpkDispRel
		n++
		haveTarget = true
	}

	if a.RegMaskDst != 0 {
		kinds[n] = instructions.OpkRegList
		n++
	} else if a.FPRegMaskDst != 0 {
		kinds[n] = instructions.OpkFPRegList
		n++
	} else if a.FPCtrlMaskDst != 0 {
		kinds[n] = instructions.OpkFPCtrlRegList
		n++
	} else if a.Dst.Kind != instructions.EAkNone {
		kinds[n] = operandKindFromEA(a.Dst)
		n++
	}

	if a.Aux.Kind != instructions.EAkNone {
		kinds[n] = operandKindFromEA(a.Aux)
		n++
	}

	if a.Aux2.Kind != instructions.EAkNone {
		kinds[n] = operandKindFromEA(a.Aux2)
		n++
	}

	if (a.Target != "" || a.HasTargetAddr) && !haveTarget {
		kinds[n] = instructions.OpkDispRel
		n++
	}

	return kinds[:n]
}

var operandKindByEA = map[instructions.EAExprKind]instructions.OperandKind{
	instructions.EAkNone:        instructions.OpkNone,
	instructions.EAkImm:         instructions.OpkImm,
	instructions.EAkDn:          instructions.OpkDn,
	instructions.EAkAn:          instructions.OpkAn,
	instructions.EAkAddrPredec:  instructions.OpkPredecAn,
	instructions.EAkAddrPostinc: instructions.OpkPostincAn,
	instructions.EAkSR:          instructions.OpkSR,
	instructions.EAkCCR:         instructions.OpkCCR,
	instructions.EAkUSP:         instructions.OpkUSP,
	instructions.EAkSFC:         instructions.OpkCtrlReg,
	instructions.EAkDFC:         instructions.OpkCtrlReg,
	instructions.EAkVBR:         instructions.OpkCtrlReg,
	instructions.EAkFPn:         instructions.OpkFPn,
	instructions.EAkRegPair:     instructions.OpkRegPair,
	instructions.EAkAnIndPair:   instructions.OpkAnIndPair,
	instructions.EAkTC:          instructions.OpkTC,
	instructions.EAkCacheSel:    instructions.OpkCacheSel,
	instructions.EAkCRP:         instructions.OpkCRP,
	instructions.EAkSRP:         instructions.OpkSRP,
	instructions.EAkTT0:         instructions.OpkTT0,
	instructions.EAkTT1:         instructions.OpkTT1,
	instructions.EAkMMUSR:       instructions.OpkMMUSR,
	instructions.EAkDRP:         instructions.OpkDRP,
	instructions.EAkCAL:         instructions.OpkCAL,
	instructions.EAkVAL:         instructions.OpkVAL,
	instructions.EAkSCC:         instructions.OpkSCC,
	instructions.EAkAC:          instructions.OpkAC,
	instructions.EAkPCSR:        instructions.OpkPCSR,
	instructions.EAkBAD:         instructions.OpkBAD,
	instructions.EAkBAC:         instructions.OpkBAC,
	instructions.EAkFCSpec:      instructions.OpkFCSpec,
	instructions.EAkFPRegPair:   instructions.OpkFPRegPair,
}

// operandKindFromEA classifies an EA expression into the broader operand kind categories
// used by instruction form matching, defaulting to OpkEA for generic addressing modes.
func operandKindFromEA(e instructions.EAExpr) instructions.OperandKind {
	if kind, ok := operandKindByEA[e.Kind]; ok {
		return kind
	}
	return instructions.OpkEA
}

func operKindsMatch(expected, actual []instructions.OperandKind) bool {
	if len(expected) != len(actual) {
		return false
	}
	for i := range expected {
		if !operandKindCompatible(expected[i], actual[i]) {
			return false
		}
	}
	return true
}

func operandKindCompatible(expect, actual instructions.OperandKind) bool {
	if expect == actual {
		return true
	}
	if expect == instructions.OpkEA {
		switch actual {
		case instructions.OpkEA, instructions.OpkDn, instructions.OpkAn, instructions.OpkImm, instructions.OpkPredecAn, instructions.OpkPostincAn:
			return true
		}
	}
	// USP is also a MOVEC control register (EAkUSP maps to OpkUSP so
	// MOVE USP,An/An,USP keep working unchanged), so a form requiring
	// OpkCtrlReg must accept an OpkUSP operand too.
	if expect == instructions.OpkCtrlReg && actual == instructions.OpkUSP {
		return true
	}
	return false
}

func itemLocation(it any) (pc uint32, line int, ok bool) {
	switch v := it.(type) {
	case *Instr:
		return v.PC, v.Line, true
	case *DataBytes:
		return v.PC, v.Line, true
	default:
		return 0, 0, false
	}
}
